#!/bin/bash

echo "🔧 QUICK START GUIDE"
echo "==================="
echo ""
echo "Your Executive Assistant + n8n automation is 95% ready!"
echo ""
echo -e "\033[1;33m⚠️  REQUIRED: Add your OpenAI API key\033[0m"
echo ""
echo "1. Edit the environment file:"
echo "   nano automation/n8n/.env"
echo ""
echo "2. Replace 'your_openai_api_key_here' with your actual API key:"
echo "   OPENAI_API_KEY=sk-your-actual-key-here"
echo ""
echo "3. Save and exit (Ctrl+X, then Y, then Enter)"
echo ""
echo "4. Start the integrated environment:"
echo "   ./scripts/start-with-automation.sh"
echo ""
echo "5. Configure n8n workflows:"
echo "   • Open http://localhost:5678"
echo "   • Login: admin / ExecutiveAssistant2025!"
echo "   • Import workflows from automation/n8n/workflows/"
echo ""
echo "6. Test automation:"
echo "   ./scripts/test-automation.sh"
echo ""
echo -e "\033[1;32m🎉 Then enjoy your AI-powered Executive Assistant!\033[0m"
